# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/gRPC/service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'app/gRPC/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/gRPC/service.proto\x12\x05\x61iAPI\"C\n\x12UploadFilesRequest\x12\x1a\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0b.aiAPI.File\x12\x11\n\tclassName\x18\x02 \x01(\t\"&\n\x04\x46ile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\"=\n\x13UploadFilesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerrorMessages\x18\x02 \x03(\t\"8\n\x10SendAudioRequest\x12\x11\n\taudioData\x18\x01 \x01(\x0c\x12\x11\n\tclassName\x18\x02 \x01(\t\";\n\x11SendAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerrorMessages\x18\x02 \x03(\t\":\n\x13SendQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x11\n\tclassName\x18\x02 \x01(\t\"N\n\x14SendQuestionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerrorMessages\x18\x02 \x03(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t2\x99\x01\n\x0eSessionManager\x12>\n\tSendAudio\x12\x17.aiAPI.SendAudioRequest\x1a\x18.aiAPI.SendAudioResponse\x12G\n\x0cSendQuestion\x12\x1a.aiAPI.SendQuestionRequest\x1a\x1b.aiAPI.SendQuestionResponse2T\n\x0c\x43lassManager\x12\x44\n\x0bUploadFiles\x12\x19.aiAPI.UploadFilesRequest\x1a\x1a.aiAPI.UploadFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.gRPC.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILESREQUEST']._serialized_start=33
  _globals['_UPLOADFILESREQUEST']._serialized_end=100
  _globals['_FILE']._serialized_start=102
  _globals['_FILE']._serialized_end=140
  _globals['_UPLOADFILESRESPONSE']._serialized_start=142
  _globals['_UPLOADFILESRESPONSE']._serialized_end=203
  _globals['_SENDAUDIOREQUEST']._serialized_start=205
  _globals['_SENDAUDIOREQUEST']._serialized_end=261
  _globals['_SENDAUDIORESPONSE']._serialized_start=263
  _globals['_SENDAUDIORESPONSE']._serialized_end=322
  _globals['_SENDQUESTIONREQUEST']._serialized_start=324
  _globals['_SENDQUESTIONREQUEST']._serialized_end=382
  _globals['_SENDQUESTIONRESPONSE']._serialized_start=384
  _globals['_SENDQUESTIONRESPONSE']._serialized_end=462
  _globals['_SESSIONMANAGER']._serialized_start=465
  _globals['_SESSIONMANAGER']._serialized_end=618
  _globals['_CLASSMANAGER']._serialized_start=620
  _globals['_CLASSMANAGER']._serialized_end=704
# @@protoc_insertion_point(module_scope)
