# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.gRPC import service_pb2 as app_dot_gRPC_dot_service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/gRPC/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAudio = channel.unary_unary(
                '/aiAPI.SessionManager/SendAudio',
                request_serializer=app_dot_gRPC_dot_service__pb2.SendAudioRequest.SerializeToString,
                response_deserializer=app_dot_gRPC_dot_service__pb2.SendAudioResponse.FromString,
                _registered_method=True)
        self.SendQuestion = channel.unary_unary(
                '/aiAPI.SessionManager/SendQuestion',
                request_serializer=app_dot_gRPC_dot_service__pb2.SendQuestionRequest.SerializeToString,
                response_deserializer=app_dot_gRPC_dot_service__pb2.SendQuestionResponse.FromString,
                _registered_method=True)


class SessionManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAudio,
                    request_deserializer=app_dot_gRPC_dot_service__pb2.SendAudioRequest.FromString,
                    response_serializer=app_dot_gRPC_dot_service__pb2.SendAudioResponse.SerializeToString,
            ),
            'SendQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.SendQuestion,
                    request_deserializer=app_dot_gRPC_dot_service__pb2.SendQuestionRequest.FromString,
                    response_serializer=app_dot_gRPC_dot_service__pb2.SendQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiAPI.SessionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiAPI.SessionManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiAPI.SessionManager/SendAudio',
            app_dot_gRPC_dot_service__pb2.SendAudioRequest.SerializeToString,
            app_dot_gRPC_dot_service__pb2.SendAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiAPI.SessionManager/SendQuestion',
            app_dot_gRPC_dot_service__pb2.SendQuestionRequest.SerializeToString,
            app_dot_gRPC_dot_service__pb2.SendQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClassManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFiles = channel.unary_unary(
                '/aiAPI.ClassManager/UploadFiles',
                request_serializer=app_dot_gRPC_dot_service__pb2.UploadFilesRequest.SerializeToString,
                response_deserializer=app_dot_gRPC_dot_service__pb2.UploadFilesResponse.FromString,
                _registered_method=True)


class ClassManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=app_dot_gRPC_dot_service__pb2.UploadFilesRequest.FromString,
                    response_serializer=app_dot_gRPC_dot_service__pb2.UploadFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiAPI.ClassManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiAPI.ClassManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiAPI.ClassManager/UploadFiles',
            app_dot_gRPC_dot_service__pb2.UploadFilesRequest.SerializeToString,
            app_dot_gRPC_dot_service__pb2.UploadFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
